# Generated by Django 5.2.11 on 2026-02-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cca3', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('capital', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('subregion', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.BigIntegerField(default=0)),
                ('area', models.FloatField(default=0)),
                ('flag_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
